name: Scrape Novels

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '30 */6 * * *' # Adjust as needed

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        batch: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Install Chrome for Puppeteer
        run: npx puppeteer browsers install chrome
      - name: Set up environment variables
        run: |
          echo "XATA_API_KEY=${{ secrets.XATA_API_KEY }}" >> $GITHUB_ENV
          echo "XATA_BRANCH=main" >> $GITHUB_ENV
          # echo "XATA_DATABASE_URL=https://Infinity-Free-Fire-s-workspace-ntm0uo.us-east-1.xata.sh/db/webnovelvault2" >> $GITHUB_ENV
      - name: Run scraper for batch
        run: node main.js ${{ matrix.batch }}
